import sqlite3 as lite
import sys
import time

con = lite.connect("hotspot.db")

with con:
    cur = con.cursor()

    cur.execute("CREATE TABLE IF NOT EXISTS Participant (Participant_id INTEGER PRIMARY KEY, Name TEXT, Age INTEGER, Gender TEXT)")
    cur.execute("CREATE TABLE IF NOT EXISTS Destination (Dest_id INTEGER PRIMARY KEY, Dest_name TEXT, State TEXT, City TEXT)")
    cur.execute("CREATE TABLE IF NOT EXISTS Event (Event_id INTEGER PRIMARY KEY, Event_name TEXT, Dest_id INTEGER, Start_time DATETIME, End_time DATETIME, Description TEXT, Cat_id INTEGER, Cost FLOAT)")
    cur.execute("CREATE TABLE IF NOT EXISTS Attendance (Att_id INTEGER PRIMARY KEY, Participant_id INTEGER, Event_id INTEGER)")
    cur.execute("CREATE TABLE IF NOT EXISTS Category (Cat_id INTEGER PRIMARY KEY, Name TEXT)")
    
    
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (1, 'Andrea', 21, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (2, 'Cindy', 21, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (3, 'Ben', 21, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (4, 'Omid', 21, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (5, 'John', 19, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (6, 'Mary', 24, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (7, 'Jeffrey', 25, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (8, 'Sam', 28, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (9, 'George', 28, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (10, 'Paul', 38, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (11, 'Karen', 37, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (12, 'Jim', 28, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (13, 'Lilly', 22, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (14, 'Hannah', 28, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (15, 'Lauren', 26, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (16, 'Jonathan', 21, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (17, 'Kristen', 22, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (18, 'Nathan', 25, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (19, 'Luke', 31, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (20, 'Shelly', 22, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (21, 'Kelly', 37, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (22, 'James', 28, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (23, 'Laila', 22, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (24, 'Harriet', 28, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (25, 'Lucy', 26, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (26, 'Jared', 21, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (27, 'Barbara', 42, 'Female')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (28, 'Max', 25, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (29, 'Larry', 31, 'Male')")
    cur.execute("INSERT INTO Participant (Participant_id, Name, Age, Gender) VALUES (30, 'Shirley', 32, 'Female')")

    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (1, 'Union Square', 'California', 'San Francisco')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (2, 'Alcatraz Island', 'California', 'San Francisco')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (3, 'Bindlestiff Studio', 'California', 'San Francisco')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (4, 'Shelton Theater', 'California', 'San Francisco')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (5, 'AT&T Park', 'California', 'San Francisco')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (6, 'Golden Gate Park', 'California', 'San Francisco')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (7, 'Gershwin Theatre', 'New York', 'New York')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (8, 'Minskoff Theatre', 'New York', 'New York')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (9, 'New York Hall of Science', 'New York', 'New York')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (10, 'St.James Theatre', 'New York', 'New York')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (11, 'Richard Rodgers Theatre', 'New York', 'New York')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (12, 'The Museum of Modern Art', 'New York', 'New York')")
    cur.execute("INSERT INTO Destination (Dest_id, Dest_name, State, City) VALUES (13, 'The Metropolitan Museum', 'New York', 'New York')")
 

    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (1, 'Cherry Blossom Festival', 1, null, null, 'Come see the beautiful cherry blossoms!', 0, 0.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (2, 'Music Busking', 1, null, null, 'Listen to a variety of musicians play on the streets of SF.', 0, 0.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (3, 'Alcatraz Island Tour', 2, null, null, 'Tour the old prison of Alcatraz', 0, 20.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (4, 'Geek Show 2: Bindlecon', 3, null, null, 'Movie event', 0, 15.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (5, 'Late Night Improv', 4, null, null, 'A fun night of comedy', 0, 15.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (6, 'SF Giants Baseball', 5, null, null, 'Baseball yay', 0, 100.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (7, 'Outside Lands', 6, null, null, 'Bay Area finest celebration of Music, Food, Wine, Beer, Art & Comedy', 0, 150.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (8, 'Wicked', 7, null, null, 'A must see', 0, 120.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (9, 'The Lion King', 8, null, null, 'Experience this awe-inspiring Broadway spectacular', 0, 180.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (10, 'America's Musical Journey', 9, null, null, 'Learn about America's Musical Journey', 0, 60.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (11, 'Frozen', 10, null, null, 'Let it go', 0, 90.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (12, 'Hamilton', 11, null, null, 'A broadway spectacular', 0, 140.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (13, 'Afternoon', 12, null, null, 'A special exhibit', 0, 30.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (14, 'Art at the Met', 13, null, null, 'Art', 0, 35.0)")
    cur.execute("INSERT INTO Event (Event_id, Event_name, Dest_id, Start_time, End_time, Description, Cat_id, Cost) VALUES (15, 'Japanese Tea Garden', 6, null, null, 'Gardens', 0, 0.0)")


    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (1, 1, 3)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (2, 2, 3)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (3, 3, 3)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (4, 4, 3)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (5, 5, 3)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (6, 6, 3)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (7, 7, 3)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (8, 8, 1)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (9, 1, 1)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (10, 5, 1)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (11, 8, 1)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (12, 9, 1)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (13, 10, 2)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (14, 11, 2)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (15, 12, 2)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (16, 13, 2)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (17, 14, 2)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (18, 15, 2)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (19, 16, 2)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (20, 17, 4)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (21, 18, 4)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (22, 19, 4)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (23, 20, 4)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (24, 19, 5)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (25, 18, 5)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (26, 17, 5)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (27, 16, 5)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (28, 15, 5)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (29, 14, 6)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (30, 13, 6)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (31, 12, 6)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (32, 11, 6)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (33, 10, 6)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (34, 12, 6)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (35, 12, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (36, 13, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (37, 14, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (38, 15, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (39, 16, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (40, 17, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (41, 18, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (42, 19, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (43, 20, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (44, 12, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (45, 13, 7)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (46, 14, 7)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (47, 1, 8)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (48, 2, 8)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (49, 3, 8)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (50, 4, 8)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (51, 5, 8)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (52, 6, 8)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (53, 7, 9)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (54, 8, 9)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (55, 9, 9)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (56, 10, 9)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (57, 11, 9)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (58, 12, 9)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (59, 13, 9)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (60, 14, 9)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (61, 15, 10)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (62, 16, 10)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (63, 17, 10)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (64, 18, 10)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (65, 19, 10)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (66, 20, 10)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (67, 17, 11)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (68, 18, 11)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (69, 19, 11)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (70, 20, 11)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (71, 21, 12)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (72, 22, 12)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (73, 23, 12)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (74, 24, 12)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (75, 25, 12)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (76, 26, 12)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (77, 27, 12)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (78, 28, 12)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (79, 29, 13)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (80, 30, 13)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (81, 22, 13)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (82, 23, 13)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (83, 24, 13)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (84, 25, 13)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (85, 29, 14)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (86, 30, 14)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (87, 12, 14)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (88, 13, 14)")

    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (89, 1, 15)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (90, 3, 15)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (91, 5, 15)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (92, 7, 15)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (93, 9, 15)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (94, 11, 15)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (95, 13, 15)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (96, 15, 15)")
    cur.execute("INSERT INTO Attendance (Att_id, Participant_id, Event_id) VALUES (97, 17, 15)")



    '''
    cur.execute("INSERT INTO Books (title, author) VALUES ('Info Org', 'Bob')")
    cur.execute("INSERT INTO Books (title, author) VALUES ('Info Law', 'Deidre')")
    cur.execute("INSERT INTO Books (title, author) VALUES ('Math', 'Julie')")
    '''